# code --list-extensions | xargs -L 1 echo code --install-extension
code --install-extension adpyke.vscode-sql-formatter
code --install-extension alpha4.jsonl
code --install-extension dbaeumer.vscode-eslint
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension editorconfig.editorconfig
code --install-extension esbenp.prettier-vscode
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension github.vscode-github-actions
code --install-extension golang.go
code --install-extension hashicorp.terraform
code --install-extension jock.svg
code --install-extension ms-python.debugpy
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-vscode.makefile-tools
code --install-extension redhat.vscode-xml
code --install-extension reduckted.vscode-gitweblinks
code --install-extension rust-lang.rust-analyzer
code --install-extension rvest.vs-code-prettier-eslint
code --install-extension shopify.ruby-lsp
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension stylelint.vscode-stylelint
code --install-extension toba.vsfire
code --install-extension usernamehw.errorlens
code --install-extension vayan.haml
code --install-extension vscodevim.vim
code --install-extension zixuanchen.vitest-explorer
